In [51]:
import tensorflow as tf
from tensorflow.keras.models import model_from_json
from flask import Flask, render_template, request
import numpy as np
from keras.models import load_model
import pickle
import tensorflow as tf
# # Load the model architecture from JSON file
# with open('my_keras_model.json', 'r') as json_file:
#     loaded_model_json = json_file.read()
# loaded_model = model_from_json(loaded_model_json)

# # Load the model weights
# loaded_model.load_weights("my_keras_model_weights.h5")

# # Now you can use the loaded model for predictions


In [52]:
import pickle
preprocessing_pipe = pickle.load(open('pipepreprocessingu_val.pkl', 'rb'))
loaded_model=load_model('my_uval_model.keras')


In [53]:
import numpy as np

In [59]:
import numpy as np
from keras.models import load_model
import pickle
import tensorflow as tf

# Load preprocessed pipeline
# Load Keras model

# Function to prompt user for input and make predictions
def make_prediction():
    # Prompt user for input
    # climaticZone = str(input("Enter climatic zone: "))
    # latitude = float(input("Enter latitude: "))
    # longitude = float(input("Enter longitude: "))
    # shadeExtent = float(input("Enter shade extent: "))
    # roofUValue = float(input("Enter roof U-value: "))
    # heightOfShade = float(input("Enter height of shade: "))
    # shadingTransmittance = float(input("Enter shading transmittance: "))
    # buildingOrientation = float(input("Enter building orientation: "))
    # shadeDirection = str(input("Enter shade direction: "))

    
    latitude = 17.67
    longitude = 75.91
    savings=18
    
    
    # Create input data array
    input_data = np.array([latitude, longitude,savings]).reshape(1, -1)
    preprocessed_input = preprocessing_pipe.transform(input_data)
    return preprocessed_input
preprocessed_input=make_prediction()
print("Preprocessed input data:")
print(preprocessed_input)
#     # Make predictions
#     result = keras_model.predict(preprocessed_input)

#     return result[0][0]

# # Call the function to make a prediction
# prediction = make_prediction()  West

# print("Predicted result:", prediction)


Preprocessed input data:
[[0.39602248 0.17278839 0.88421053]]


C:\Users\Amresh Gupta\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [60]:
preprocessed_input.dtype

dtype('float64')

In [61]:
preprocessed_input = preprocessed_input.astype(np.float64)
preprocessed_input.dtype

dtype('float64')

In [62]:
preprocessed_input

array([[0.39602248, 0.17278839, 0.88421053]])

In [63]:
# Make predictions
result = loaded_model.predict(preprocessed_input)
result[0][0]

1/1 [==============================] - 0s 17ms/step


0.7952397

In [14]:
import numpy as np
import pandas as pd
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import tensorflow as tf
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder


In [15]:
raw_data=pd.read_csv('12.01.2024 Wakanda Final for analysis _CSV format1.csv')

In [60]:
raw_data.rename(columns={'Top floor C&H savings (%)': 'savings'}, inplace= True)
savings_per=raw_data.savings.str.replace('%','').astype('float')
raw_data['Savings_Percentage']=savings_per

In [61]:
columns_name=[ '#','City','c0: Total Energy', 'Total Energy Savings (%)',
       'c1: Total Cooling', 'Top Floor_Total Cooling',
       'Top Floor_Total Heating', 'Top Floor _ total C&H', 'savings',
       'Topfloor Cooling Savings (%)']
raw_data.drop(columns_name,axis=1,inplace=True)


In [62]:
raw_data['Building Orientation']=raw_data['Building Orientation'].astype(str)

In [63]:
raw_data.columns

Index(['Climatic Zone', 'Shade Direction', 'Building Orientation',
       'Latitude (Deg North)', 'Longitude (Deg East)', 'Shade extent ',
       'Roof U-Value (W/m2K)', 'Height of Shade (m)', 'Shading Transmittance',
       'Savings_Percentage'],
      dtype='object')

In [64]:
X_train, X_test, y_train, y_test = train_test_split(raw_data.drop(columns=['Savings_Percentage']),raw_data['Savings_Percentage'], test_size = 0.08, random_state = 0,stratify=raw_data['Savings_Percentage'])

In [65]:
preprocessed_x_train=preprocessing_pipe.transform(X_train)

In [66]:
result = loaded_model.predict(preprocessed_x_train)


17222/17222 [==============================] - 15s 893us/step


In [67]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Assuming y_pred contains your predicted values
mae = mean_absolute_error(y_train, result)
mse = mean_squared_error(y_train,result)
r2 = r2_score(y_train, result)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Absolute Error: 0.39644298833977376
Mean Squared Error: 0.2798038849667943
R-squared: 0.9974967966154514


In [73]:
kk = raw_data['Latitude (Deg North)'].unique()


In [74]:
kk

array([17.67, 19.88, 23.26, 26.85, 28.61, 31.64, 30.32, 18.52, 21.17,
       23.03, 24.58, 26.92, 28.02, 15.14, 17.38, 21.15, 12.97,  8.51,
       10.79, 12.92, 13.08, 17.69, 15.49, 19.07, 22.57, 25.57])

In [75]:
jj = raw_data['Longitude (Deg East)'].unique()


In [76]:
jj

array([75.9064, 75.3433, 77.4126, 80.9462, 77.209 , 74.8737, 78.0322,
       73.8567, 72.8311, 72.5714, 73.7125, 75.7873, 73.3119, 76.9214,
       78.4867, 79.0882, 77.5946, 76.9366, 78.7047, 74.856 , 80.2707,
       83.2185, 73.8278, 72.8777, 88.3639, 91.8933])

In [77]:
kk = [17.67, 19.88, 23.26, 26.85, 28.61, 31.64, 30.32, 18.52, 21.17,
       23.03, 24.58, 26.92, 28.02, 15.14, 17.38, 21.15, 12.97,  8.51,
       10.79, 12.92, 13.08, 17.69, 15.49, 19.07, 22.57, 25.57]
jj=[75.9064, 75.3433, 77.4126, 80.9462, 77.209 , 74.8737, 78.0322,
       73.8567, 72.8311, 72.5714, 73.7125, 75.7873, 73.3119, 76.9214,
       78.4867, 79.0882, 77.5946, 76.9366, 78.7047, 74.856 , 80.2707,
       83.2185, 73.8278, 72.8777, 88.3639, 91.8933]
r=22.8 j=75
'i want to return cmbined nearest both values'
r_modified=nearestof([kk])
j_modified=nearestof([jj])

In [79]:
import numpy as np

# Assuming kk is the array of unique latitude values
kk = raw_data['Latitude (Deg North)'].unique()

# Given value
r = 22.8

# Calculate absolute differences
differences = np.abs(kk - r)

# Find the index of the minimum difference
nearest_index = np.argmin(differences)

# Nearest value
nearest_value = kk[nearest_index]

# Print the nearest value

23.03


In [87]:
import numpy as np

def combined_nearest_values(value1, value2):
    """Find the combined nearest values from two arrays."""
    arr1 = np.array([17.67, 19.88, 23.26, 26.85, 28.61, 31.64, 30.32, 18.52, 21.17,
               23.03, 24.58, 26.92, 28.02, 15.14, 17.38, 21.15, 12.97,  8.51,
               10.79, 12.92, 13.08, 17.69, 15.49, 19.07, 22.57, 25.57])
    arr2 = np.array([75.9064, 75.3433, 77.4126, 80.9462, 77.209 , 74.8737, 78.0322,
               73.8567, 72.8311, 72.5714, 73.7125, 75.7873, 73.3119, 76.9214,
               78.4867, 79.0882, 77.5946, 76.9366, 78.7047, 74.856 , 80.2707,
               83.2185, 73.8278, 72.8777, 88.3639, 91.8933])
    
    min_diff = float('inf')
    nearest_combined_values = None
    
    for v1 in arr1:
        for v2 in arr2:
            diff = abs(v1 - value1) + abs(v2 - value2)
            if diff < min_diff:
                min_diff = diff
                nearest_combined_values = (v1, v2)
    
    return nearest_combined_values
r = 20.0  
j = 80.0  
r,j = combined_nearest_values(r,j)




r 19.88


In [81]:
r

20.0